// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: geecachepb.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GroupCacheService_Get_FullMethodName = "/geecachepb.GroupCacheService/Get"
)

// GroupCacheServiceClient is the client API for GroupCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupCacheServiceClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type groupCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupCacheServiceClient(cc grpc.ClientConnInterface) GroupCacheServiceClient {
	return &groupCacheServiceClient{cc}
}

func (c *groupCacheServiceClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, GroupCacheService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupCacheServiceServer is the server API for GroupCacheService service.
// All implementations must embed UnimplementedGroupCacheServiceServer
// for forward compatibility
type GroupCacheServiceServer interface {
	Get(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGroupCacheServiceServer()
}

// UnimplementedGroupCacheServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGroupCacheServiceServer struct {
}

func (UnimplementedGroupCacheServiceServer) Get(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGroupCacheServiceServer) mustEmbedUnimplementedGroupCacheServiceServer() {}

// UnsafeGroupCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupCacheServiceServer will
// result in compilation errors.
type UnsafeGroupCacheServiceServer interface {
	mustEmbedUnimplementedGroupCacheServiceServer()
}

func RegisterGroupCacheServiceServer(s grpc.ServiceRegistrar, srv GroupCacheServiceServer) {
	s.RegisterService(&GroupCacheService_ServiceDesc, srv)
}

func _GroupCacheService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupCacheServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupCacheService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupCacheServiceServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupCacheService_ServiceDesc is the grpc.ServiceDesc for GroupCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geecachepb.GroupCacheService",
	HandlerType: (*GroupCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GroupCacheService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geecachepb.proto",
}
